### ISSUE TITLE
Sonar impovements

### ISSUE THREAD

**Issue by SergeOlabin** [ita-social-projects/dokazovi-fe#100]
Investigate sonar following improvements:
- check the possibility to configure the coverage % necessary, so that we can change 80% required as a default
- check if it's possible to configure the rules for Code Smells, to turn off some rules.

**Comment by Gtes** [comment]
Waiting for feedback regarding CG.
ref: https://samlearnsazure.blog/2019/06/21/customizing-sonarcloud-rule-sets/

**Comment by KarkabsisV** [comment]
We have access to create custom Quality Gate
