### ISSUE TITLE
Post Creation: Add spinner to the Publish button 

### ISSUE THREAD

**Issue by AntonGluschuk** [ita-social-projects/dokazovi-fe#224]
### Task description
Add spinner to the Publish button due to the next problem:
When user finish write main content of the post (on Create Article/ Create Note pages) and click **Publish** button too fast his post wouldn't be sent to BE due to 2-sec timeout of the useCallback hook:

**ArticleCreation.ts**
![image](https://user-images.githubusercontent.com/32397351/106278264-1b94ce80-6243-11eb-9e30-6364ea2b0769.png)

### To do 
1. - [ ] Add spinner to the Publish button

**Comment by calster00** [comment]
We could store button status (enabled/disabled) in redux. Set it disabled on input change using debounced call (leading). Then enable it again from dispatchHtmlContent call.
