### ISSUE TITLE
Editor: Fix upload image on the localhost

### ISSUE THREAD

**Issue by AntonHlushchuk** [ita-social-projects/dokazovi-fe#242]
### Task description
Editor toolbar: (upload image option)
Research solution to upload image on the localhost;

Advice:
Try CORS Anywhere approach.
Use fetch instead of axios with mode - no-cors. (Write custom request with fetch)
Current result:
![image](https://user-images.githubusercontent.com/32397351/108077040-c3e4c880-7074-11eb-9fa0-ff5bdcd167f8.png)
![image](https://user-images.githubusercontent.com/32397351/108077120-dc54e300-7074-11eb-83ef-e470f6336b5f.png)

Useful link: 
[Imgur API doc](https://apidocs.imgur.com/)

### To do 
1. - [ ] Fix upload image on the localhost.

**Comment by dusty3ntity** [comment]
To bypass the Imgur restriction of uploading an image from the localhost you just have to go to `127.0.0.1:3000` instead of `localhost:3000` in your browser. This will make your application's host `127.0.0.1`. No additional config required.

**Comment by dusty3ntity** [comment]
Unfortunately, Imgur blocks viewing uploaded images from `127.0.0.1`...
So we have such a situation:
- Imgur blocks uploading images from `localhost`
- Imgur blocks viewing uploaded images from `127.0.0.1`

Well, the solution is just to use everything, except `localhost` and `127.0.0.1`. For example, use `127.0.0.2`.
Or you can just configure your `hosts` file to proxy, for example, `imgurtest` to `localhost` to avoid these confusing restrictions.
