### ISSUE TITLE
Editor: Fix title positioning during image alignment 

### ISSUE THREAD

**Issue by AntonHlushchuk** [ita-social-projects/dokazovi-fe#243]
### Task description
We are using an external image resize module called (**quill-image-resize-module-react**)

Current alignment use inline styles on the ```img tag``` that cause title repositioning:

![image](https://user-images.githubusercontent.com/32397351/108078407-520d7e80-7076-11eb-9e89-8f7fb28bced5.png)

Expected result: title must be always below image.

### To do 
1. - [ ] Fix title positioning during image alignment;

**Comment by SergeOlabin** [comment]
try to play with figcation absolute pisitioning
