### ISSUE TITLE
Video: DnD

### ISSUE THREAD

**Issue by SergeOlabin** [ita-social-projects/dokazovi-fe#273]
### Task description
After Create Video page is ready, implement a solution to drag and drop video elements 

### To do 
1. - [ ] check https://github.com/atlassian/react-beautiful-dnd (seems better to me) or https://github.com/react-dnd/react-dnd/ or another DnD library
2. - [ ] DnD for videos 
3. - [ ] highligh drop area
4. - [ ] don't allow other but video file types

**Comment by jeka-leb** [comment]
BA representatives offered to postpone this issue and come back again within a particular Sprint Log associated with it.
