### ISSUE TITLE
Fix: Error while creating new post (create article, video, note)

### ISSUE THREAD

**Issue by AnnaMinasian** [ita-social-projects/dokazovi-fe#308]
### Task description

fix error when creating a new post(video, note, article)

<img width="1129" alt="Screenshot 2021-03-12 at 13 44 05" src="https://user-images.githubusercontent.com/32515945/110938922-493e5e80-833d-11eb-8a35-b981dcd9dc2e.png">

### To do

1. - [ ] fix error while creating new post

**Comment by SergeOlabin** [comment]
duplicate https://github.com/ita-social-projects/dokazovi-fe/issues/311
