### ISSUE TITLE
SPIKE "Browser Object Model (BOM)"

### ISSUE THREAD

**Issue by VitaliiKulinskyi** [ita-social-projects/dokazovi-fe#420]
### Task description

Make investigation about Browser Object Model (BOM)

### To do

1. - [x] What is Browser Object Model (BOM)
2. - [x] What is the role of Browser Object Model (BOM) in JavaScript?
3. - [x] Examples of BOM use
4. - [x] Make a presentation

**Comment by Valentyna-Chudik** [comment]
[BOM presentation](https://1drv.ms/p/s!AgSg0ommV9G9gcUoQCuABGZNTIMdIg?e=rDocN6)
