### ISSUE TITLE
SPIKE #6: Unit Tests React

### ISSUE THREAD

**Issue by KarkabsisV** [ita-social-projects/dokazovi-fe#8]
AC:

- [x] Research and compare libraries for Unit Test
- [x] Presentation 
- [x] WikiPage 
- [ ] Code coverage plugin for GitHub
 
Useful links: 
https://reactjs.org/docs/testing.html
https://jestjs.io/docs/en/tutorial-react
https://testing-library.com/docs/react-testing-library/example-intro/

**Comment by SergeOlabin** [comment]
Code coverage plugin for GitHub - start with researching how to get a code coverage i.e. from the CLI.

@KarkabsisV do we need to integrate the coverage with the github ? and what's out motivation in this case?
